Villa.Web/Models/Dtos/VIllaNumber/VillaNumberCreateDto.cs
using System.ComponentModel.DataAnnotations;

namespace Villa.Web.Models.Dtos.VIllaNumber;

public class VillaNumberCreateDto
{
    public int VillaNo { get; set; }
    public string SpecialDetails { get; set; } = string.Empty;
    public int VillaId { get; set; }

}

Villa.Web/Models/Dtos/VIllaNumber/VillaNumberDto.cs
using System.ComponentModel.DataAnnotations;

namespace Villa.Web.Models.Dtos.VIllaNumber;

public class VillaNumberDto
{
    public int VillaNo { get; set; }
    public string SpecialDetails { get; set; } = string.Empty;

}

Villa.Web/Models/Dtos/VIllaNumber/VillaNumberUpdateDto.cs
using System.ComponentModel.DataAnnotations;

namespace Villa.Web.Models.Dtos.VIllaNumber;

public class VillaNumberUpdateDto
{
    public int VillaNo { get; set; }
    public string SpecialDetails { get; set; } = string.Empty;
    public int VillaId { get; set; }

}

Villa.Web/Models/Dtos/Villa/VillaCreateDto.cs
using System.ComponentModel.DataAnnotations;

namespace Villa.Web.Models.Dtos.Villa;

public class VillaCreateDto
{
    [MaxLength(30)]
    public string Name { get; set; }

    public int Sqft { get; set; }

    public int Occupancy { get; set; }

    public double Rate { get; set; }

    public string? ImageUrl { get; set; }
    public string? Amenity { get; set; }
    public string? Details { get; set; }
}

Villa.Web/Models/Dtos/Villa/VillaDto.cs
using System.ComponentModel.DataAnnotations;

namespace Villa.Web.Models.Dtos.Villa;

public class VillaDto
{
    public int Id { get; set; }
    [Required]
    [MaxLength(30)]
    public string Name { get; set; }
    public int Sqft { get; set; }
    [Required]
    public int Occupancy { get; set; }
    [Required]
    public double Rate { get; set; }
    public string ImageUrl { get; set; }
    public string Amenity { get; set; }
    public string Details { get; set; }
}

Villa.Web/Models/Dtos/Villa/VillaUpdateDto.cs
using System.ComponentModel.DataAnnotations;

namespace Villa.Web.Models.Dtos.Villa;

public class VillaUpdateDto
{
    public int Id { get; set; }
    [Required]
    [MaxLength(30)]
    public string Name { get; set; }
    public int Sqft { get; set; }
    [Required]
    public int Occupancy { get; set; }
    [Required]
    public double Rate { get; set; }
    [Required]
    public string ImageUrl { get; set; }
    [Required]
    public string Amenity { get; set; }
    public string Details { get; set; }
}

Villa.Web/Models/ErrorViewModel.cs
namespace Villa.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Villa.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Villa.Web.Models;

namespace Villa.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Villa.Web/Controllers/VillaController.cs
using Microsoft.AspNetCore.Mvc;
using Villa.Web.Models.Dtos.Villa;
using Villa.Web.Services.IServices;

namespace Villa.Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaApiClient _villaApiClient;

        public VillaController(IVillaApiClient villaApiClient)
        {
            _villaApiClient = villaApiClient;
        }

        public async Task<IActionResult> Index()
        {
            var villas = await _villaApiClient.GetAllVillasAsync();
            return View(villas);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VillaCreateDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            var createdVilla = await _villaApiClient.CreateVillaAsync(dto);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            if (id is 0)
            {
                return BadRequest();
            }
            var villa = await _villaApiClient.GetVillaAsync(id);
            return View(villa);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int idVillaUpdateDto dto)
        {
            if (ModelState.IsValid)
            {
                return View(dto);
            }

            await _villaApiClient.UpdateVillaAsync(id, dto);
            return RedirectToAction(nameof(Index));
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            if (id is 0)
            {
                return BadRequest();
            }
            await _villaApiClient.DeleteVillaAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Villa.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Villa.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Villa.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Villa.Web.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Villa.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa"
                                asp-action="Index">Villas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">@RenderBody()</main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Villa.Web -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Villa.Web/Views/Villa/Create.cshtml
@model VillaCreateDto

<div class="container mt-4">
    <h2 class="text-primary mb-4">Create Villa</h2>
    <form method="POST" asp-action="Create">
        <div class="row g-3">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" type="text">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="Sqft" class="form-label"></label>
                    <input asp-for="Sqft" class="form-control" type="number">
                    <span asp-validation-for="Sqft" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="Occupancy" class="form-label"></label>
                    <input asp-for="Occupancy" class="form-control" type="number">
                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Rate" class="form-label"></label>
                    <input asp-for="Rate" class="form-control" type="number" step="0.01">
                    <span asp-validation-for="Rate" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label asp-for="Amenity" class="form-label"></label>
                    <input asp-for="Amenity" class="form-control" type="text">
                    <span asp-validation-for="Amenity" class="text-danger"></span>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <label asp-for="Details" class="form-label"></label>
                    <textarea asp-for="Details" class="form-control" rows="3"></textarea>
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-6">
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
            <div class="col-6 text-end">
                <button type="submit" class="btn btn-primary">Create Villa</button>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Villa.Web/Views/Villa/Index.cshtml
@model IEnumerable<VillaDto>
<div class="container-fluid pt-4 border">
    <div class="row">
        <div class="col">
            <h1 class="text-primary">Villa List</h1>
        </div>
        <div class="col text-end">
            <a class="btn btn-outline-primary" asp-controller="Villa" asp-action="Create">Create Villa</a>
        </div>
    </div>
    <table class="table table-boarder">
        <thead>
            <tr>
                <th>Name</th>
                <th>Occupancy</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var villa in Model)
            {
                <tr>
                    <td>@villa.Name</td>
                    <td>@villa.Occupancy</td>
                    <td>@villa.Rate.ToString("c")</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" type="button" id="action"
                                data-toggle="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">
                                Dropdown button
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item">Action</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>Name</th>
                <th>Occupancy</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
        </tfoot>
    </table>
</div>
</VillaDto>

Villa.Web/Views/Villa/Update.cshtml
@model VillaCreateDto

<div class="container mt-4">
    <h2 class="text-primary mb-4">Update Villa</h2>
    <form method="POST" asp-action="Update">
        <div class="row g-3">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" type="text">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="Sqft" class="form-label"></label>
                    <input asp-for="Sqft" class="form-control" type="number">
                    <span asp-validation-for="Sqft" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="Occupancy" class="form-label"></label>
                    <input asp-for="Occupancy" class="form-control" type="number">
                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Rate" class="form-label"></label>
                    <input asp-for="Rate" class="form-control" type="number" step="0.01">
                    <span asp-validation-for="Rate" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label asp-for="Amenity" class="form-label"></label>
                    <input asp-for="Amenity" class="form-control" type="text">
                    <span asp-validation-for="Amenity" class="text-danger"></span>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <label asp-for="Details" class="form-label"></label>
                    <textarea asp-for="Details" class="form-control" rows="3"></textarea>
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-6">
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
            <div class="col-6 text-end">
                <button type="submit" class="btn btn-primary">Update Villa</button>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}